// Copyright 2026 Borys Zaitsev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

import type { SnippetPack } from './types'

export const BUILTIN_PACK: SnippetPack = {
  id: 'builtin',
  name: 'SENU Standard',
  version: '1.0.0',
  author: 'SENU',
  description: 'Standard server administration commands',
  builtin: true,
  groups: [
    {
      id: 'system',
      name: 'System',
      nameUk: 'Система',
      icon: '🖥',
      items: [
        {
          id: 'df-h', title: 'Disk usage', titleUk: 'Використання диску',
          command: 'df -h',
          description: 'Show disk space usage in human-readable format',
          descriptionUk: 'Показує використання диску. За замовчуванням у байтах, -h — у зручному форматі (MB, GB).',
          syntax: 'df [OPTIONS] [FILE...]',
          options: [
            { flag: '-h, --human-readable', desc: 'Human-readable sizes (KB, MB, GB)', descUk: 'Зручний формат (KB, MB, GB)' },
            { flag: '-T', desc: 'Show filesystem type', descUk: 'Показати тип файлової системи' },
            { flag: '-i', desc: 'Show inode usage', descUk: 'Показати використання інодів' },
            { flag: '--total', desc: 'Display a grand total', descUk: 'Показати загальний підсумок' },
          ],
          examples: [
            { command: 'df -h', label: 'All mounted filesystems', labelUk: 'Всі змонтовані файлові системи' },
            { command: 'df -h /', label: 'Root partition only', labelUk: 'Тільки кореневий розділ' },
            { command: 'df -hT', label: 'Include filesystem type', labelUk: 'З типом файлової системи' },
          ],
        },
        {
          id: 'free-h', title: 'Memory usage', titleUk: "Пам'ять",
          command: 'free -h',
          description: 'Display RAM and swap memory usage',
          descriptionUk: "Показує використання оперативної пам'яті та swap розділу.",
          syntax: 'free [OPTIONS]',
          options: [
            { flag: '-h', desc: 'Human-readable output', descUk: 'Зручний формат виводу' },
            { flag: '-m', desc: 'Output in megabytes', descUk: 'Вивід у мегабайтах' },
            { flag: '-s N', desc: 'Continuous update every N seconds', descUk: 'Оновлення кожні N секунд' },
            { flag: '-t', desc: 'Display total row', descUk: 'Показати рядок з підсумком' },
          ],
          examples: [
            { command: 'free -h', label: 'Human-readable summary', labelUk: 'Зручний підсумок' },
            { command: 'free -h -s 2', label: 'Update every 2 seconds', labelUk: 'Оновлення кожні 2 секунди' },
            { command: 'free -m', label: 'Output in megabytes', labelUk: 'У мегабайтах' },
          ],
        },
        {
          id: 'top-n1', title: 'CPU (top)', titleUk: 'CPU (top)',
          command: 'top -b -n 1 | head -20',
          description: 'One-shot top snapshot showing top 20 lines',
          descriptionUk: 'Знімок поточного стану процесів (перші 20 рядків).',
          syntax: 'top [OPTIONS]',
          options: [
            { flag: '-b', desc: 'Batch mode (non-interactive)', descUk: 'Пакетний режим (не інтерактивний)' },
            { flag: '-n N', desc: 'Number of iterations', descUk: 'Кількість ітерацій' },
            { flag: '-u USER', desc: 'Show only user processes', descUk: 'Тільки процеси вказаного користувача' },
            { flag: '-p PID', desc: 'Monitor specific PID', descUk: 'Моніторинг конкретного PID' },
          ],
          examples: [
            { command: 'top -b -n 1 | head -20', label: 'Quick snapshot', labelUk: 'Швидкий знімок' },
            { command: 'top -u www-data', label: 'Web server processes', labelUk: 'Процеси веб-сервера' },
            { command: 'top -b -n 1 | grep -v "0.0  0.0"', label: 'Active processes only', labelUk: 'Тільки активні процеси' },
          ],
        },
        { id: 'uname-r', title: 'Kernel version', titleUk: 'Версія ядра', command: 'uname -r', description: 'Show running kernel version', descriptionUk: 'Показує версію запущеного ядра Linux.' },
        { id: 'uptime', title: 'Uptime', titleUk: 'Uptime', command: 'uptime -p', description: 'Show how long the system has been running', descriptionUk: 'Показує скільки часу система працює без перезавантаження.' },
        { id: 'who', title: 'Who is logged in', titleUk: 'Хто увійшов', command: 'who', description: 'Show logged-in users' },
        { id: 'last-n20', title: 'Last logins', titleUk: 'Останні входи', command: 'last -n 20', description: 'Show last 20 login sessions' },
        { id: 'systemctl-running', title: 'Running services', titleUk: 'Запущені сервіси', command: 'systemctl list-units --type=service --state=running', description: 'List all currently running systemd services' },
        { id: 'journalctl-err', title: 'Journal errors', titleUk: 'Помилки journald', command: 'journalctl -p err -n 50 --no-pager', description: 'Show last 50 error messages from system journal' },
        { id: 'ss-tulpn', title: 'Open ports', titleUk: 'Відкриті порти', command: 'ss -tulpn', description: 'List all listening TCP/UDP ports with process names' },
        { id: 'os-release', title: 'OS release', titleUk: 'Версія ОС', command: 'cat /etc/os-release', description: 'Show OS distribution information' },
        { id: 'lscpu', title: 'CPU info', titleUk: 'Інфо CPU', command: 'lscpu | grep -E "Model|CPU\\(s\\)|MHz"', description: 'Show CPU model, count, and frequency' },
      ],
    },
    {
      id: 'network',
      name: 'Network',
      nameUk: 'Мережа',
      icon: '🌐',
      items: [
        {
          id: 'ip-addr', title: 'IP addresses', titleUk: 'IP адреси',
          command: 'ip addr show',
          description: 'Display all network interfaces and their IP addresses',
          descriptionUk: 'Показує всі мережеві інтерфейси та їхні IP адреси.',
          syntax: 'ip addr [show [DEV]]',
          options: [
            { flag: 'show', desc: 'Display addresses', descUk: 'Показати адреси' },
            { flag: 'add ADDR dev DEV', desc: 'Add IP to interface', descUk: 'Додати IP до інтерфейсу' },
            { flag: 'del ADDR dev DEV', desc: 'Remove IP from interface', descUk: 'Видалити IP з інтерфейсу' },
          ],
          examples: [
            { command: 'ip addr show', label: 'All interfaces', labelUk: 'Всі інтерфейси' },
            { command: 'ip addr show eth0', label: 'Specific interface', labelUk: 'Конкретний інтерфейс' },
            { command: 'ip -4 addr show', label: 'IPv4 only', labelUk: 'Тільки IPv4' },
          ],
        },
        { id: 'ip-route', title: 'Routing table', titleUk: 'Таблиця маршрутів', command: 'ip route', description: 'Display the IP routing table' },
        { id: 'ss-tnp', title: 'Active connections', titleUk: 'Активні з\'єднання', command: 'ss -tnp', description: 'Show established TCP connections with process names' },
        { id: 'nslookup', title: 'DNS lookup', titleUk: 'DNS запит', command: 'nslookup google.com', description: 'Perform a DNS lookup for a domain' },
        { id: 'ping', title: 'Ping gateway', titleUk: 'Ping шлюзу', command: 'ping -c 4 8.8.8.8', description: 'Send 4 ICMP pings to Google DNS' },
        { id: 'traceroute', title: 'Traceroute', titleUk: 'Traceroute', command: 'traceroute google.com', description: 'Trace the route to a remote host' },
        { id: 'netstat', title: 'Netstat sockets', titleUk: 'Сокети netstat', command: 'netstat -tulpn 2>/dev/null || ss -tulpn', description: 'List listening sockets (falls back to ss if netstat unavailable)' },
        { id: 'curl-speed', title: 'Speedtest', titleUk: 'Тест швидкості', command: 'curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -', description: 'Run a quick bandwidth speed test' },
      ],
    },
    {
      id: 'docker',
      name: 'Docker',
      nameUk: 'Docker',
      icon: '🐳',
      items: [
        {
          id: 'docker-ps', title: 'List containers', titleUk: 'Список контейнерів',
          command: 'docker ps',
          description: 'List running containers. Use -a to show all (including stopped).',
          descriptionUk: 'Показує список контейнерів. За замовчуванням — тільки запущені. Корисно для швидкого огляду стану всіх сервісів на хості.',
          syntax: 'docker ps [OPTIONS]',
          options: [
            { flag: '-a, --all', desc: 'Show all containers (default: only running)', descUk: 'Показати всі контейнери (за замовч. тільки running)' },
            { flag: '-q, --quiet', desc: 'Only display container IDs', descUk: 'Виводити тільки ID контейнерів' },
            { flag: '-s, --size', desc: 'Display total file sizes', descUk: 'Показати розмір файлової системи' },
            { flag: '--filter KEY=VAL', desc: 'Filter by condition (status, name, ancestor…)', descUk: 'Фільтрувати за умовою (status, name, ancestor...)' },
            { flag: '--format STRING', desc: 'Format output using Go template', descUk: 'Форматувати вивід Go template' },
            { flag: '-n, --last INT', desc: 'Show n last created containers', descUk: 'Показати N останніх контейнерів' },
            { flag: '--no-trunc', desc: 'Do not truncate output', descUk: 'Не обрізати вивід' },
          ],
          examples: [
            { command: 'docker ps', label: 'Running containers', labelUk: 'Список запущених контейнерів' },
            { command: 'docker ps -a', label: 'All containers (including stopped)', labelUk: 'Всі контейнери (включно зупинені)' },
            { command: 'docker ps -q', label: 'IDs only', labelUk: 'Тільки ID контейнерів' },
            { command: 'docker ps --filter "status=running"', label: 'Filter by status', labelUk: 'Фільтрація за статусом' },
            { command: 'docker ps --format "table {{.Names}}\\t{{.Status}}"', label: 'Custom format', labelUk: 'Форматований вивід' },
          ],
        },
        {
          id: 'docker-logs', title: 'Container logs (tail)', titleUk: 'Логи контейнера',
          command: 'docker logs --tail 100 -f <container>',
          description: 'Follow last 100 log lines of a container in real-time',
          descriptionUk: 'Слідкує за останніми 100 рядками логів контейнера в реальному часі.',
          syntax: 'docker logs [OPTIONS] CONTAINER',
          options: [
            { flag: '--tail N', desc: 'Show last N lines', descUk: 'Показати останні N рядків' },
            { flag: '-f, --follow', desc: 'Follow log output', descUk: 'Слідкувати за виводом' },
            { flag: '--since TIME', desc: 'Show logs since timestamp or relative (e.g. 1h)', descUk: 'Логи починаючи з часу (або відносно: 1h)' },
            { flag: '-t, --timestamps', desc: 'Show timestamps', descUk: 'Показувати часові мітки' },
          ],
          examples: [
            { command: 'docker logs --tail 100 -f <container>', label: 'Follow last 100 lines', labelUk: 'Слідкувати за останніми 100 рядками' },
            { command: 'docker logs --since 1h <container>', label: 'Last hour', labelUk: 'За останню годину' },
            { command: 'docker logs -t <container> 2>&1 | grep ERROR', label: 'Filter errors', labelUk: 'Фільтрація помилок' },
          ],
        },
        {
          id: 'docker-exec', title: 'Exec bash in container', titleUk: 'Bash в контейнері',
          command: 'docker exec -it <container> bash',
          description: 'Open an interactive bash shell inside a running container',
          descriptionUk: 'Відкриває інтерактивний bash всередині запущеного контейнера.',
          syntax: 'docker exec [OPTIONS] CONTAINER COMMAND',
          options: [
            { flag: '-i, --interactive', desc: 'Keep STDIN open', descUk: 'Тримати STDIN відкритим' },
            { flag: '-t, --tty', desc: 'Allocate a pseudo-TTY', descUk: 'Виділити псевдо-TTY' },
            { flag: '-u USER', desc: 'Run as specified user', descUk: 'Запустити від імені вказаного користувача' },
            { flag: '-w DIR', desc: 'Working directory inside container', descUk: 'Робоча директорія всередині контейнера' },
          ],
          examples: [
            { command: 'docker exec -it <container> bash', label: 'Open bash shell', labelUk: 'Відкрити bash' },
            { command: 'docker exec -it <container> sh', label: 'Open sh (Alpine/minimal)', labelUk: 'Відкрити sh (Alpine)' },
            { command: 'docker exec <container> ls /app', label: 'Run single command', labelUk: 'Виконати одну команду' },
          ],
        },
        { id: 'docker-images', title: 'List images', titleUk: 'Список образів', command: 'docker images', description: 'List all local Docker images' },
        { id: 'docker-stats', title: 'Container stats', titleUk: 'Статистика контейнерів', command: 'docker stats --no-stream', description: 'Show resource usage snapshot for all containers' },
        { id: 'docker-prune-img', title: 'Prune unused images', titleUk: 'Очистити образи', command: 'docker image prune -f', description: 'Remove all dangling images without confirmation' },
        { id: 'docker-prune-all', title: 'Prune everything', titleUk: 'Повне очищення', command: 'docker system prune -af', description: 'Remove all stopped containers, unused images, networks, and build cache' },
        { id: 'docker-compose-up', title: 'Compose up', titleUk: 'Compose up', command: 'docker compose up -d', description: 'Start all services defined in docker-compose.yml in detached mode' },
        { id: 'docker-compose-down', title: 'Compose down', titleUk: 'Compose down', command: 'docker compose down', description: 'Stop and remove containers, networks defined by compose' },
        { id: 'docker-compose-logs', title: 'Compose logs', titleUk: 'Compose логи', command: 'docker compose logs -f --tail 100', description: 'Follow logs from all compose services' },
        {
          id: 'docker-compose-ps', title: 'Compose status', titleUk: 'Compose статус',
          command: 'docker compose ps',
          description: 'Show status of all compose services',
          descriptionUk: 'Показує стан всіх сервісів docker compose.',
          examples: [
            { command: 'docker compose ps', label: 'All services', labelUk: 'Всі сервіси' },
            { command: 'docker compose ps --status running', label: 'Running only', labelUk: 'Тільки запущені' },
          ],
        },
      ],
    },
    {
      id: 'nginx',
      name: 'Nginx',
      nameUk: 'Nginx',
      icon: '⚡',
      items: [
        {
          id: 'nginx-test', title: 'Test config', titleUk: 'Перевірка конфігу',
          command: 'nginx -t',
          description: 'Test nginx configuration file syntax',
          descriptionUk: 'Перевіряє синтаксис конфігураційного файлу nginx без перезапуску сервісу.',
          syntax: 'nginx [OPTIONS]',
          options: [
            { flag: '-t', desc: 'Test configuration and exit', descUk: 'Перевірити конфігурацію та вийти' },
            { flag: '-T', desc: 'Test and dump config', descUk: 'Перевірити та вивести конфіг' },
            { flag: '-s SIGNAL', desc: 'Send signal: stop, quit, reload, reopen', descUk: 'Надіслати сигнал: stop, quit, reload, reopen' },
            { flag: '-c FILE', desc: 'Use alternative config file', descUk: 'Використати альтернативний файл конфігурації' },
          ],
          examples: [
            { command: 'nginx -t', label: 'Quick syntax check', labelUk: 'Перевірка синтаксису' },
            { command: 'nginx -T', label: 'Check and dump full config', labelUk: 'Перевірка з виводом конфігу' },
            { command: 'nginx -t && systemctl reload nginx', label: 'Check then reload', labelUk: 'Перевірити та перезавантажити' },
          ],
        },
        { id: 'nginx-reload', title: 'Reload', titleUk: 'Перезавантажити', command: 'systemctl reload nginx', description: 'Gracefully reload nginx without dropping connections' },
        { id: 'nginx-restart', title: 'Restart', titleUk: 'Перезапустити', command: 'systemctl restart nginx', description: 'Fully restart nginx service' },
        { id: 'nginx-status', title: 'Status', titleUk: 'Статус', command: 'systemctl status nginx', description: 'Show nginx service status and recent log lines' },
        {
          id: 'nginx-access-log', title: 'Access log (tail)', titleUk: 'Лог доступу',
          command: 'tail -f /var/log/nginx/access.log',
          description: 'Follow nginx access log in real-time',
          descriptionUk: 'Слідкує за логом доступу nginx в реальному часі.',
          examples: [
            { command: 'tail -f /var/log/nginx/access.log', label: 'Follow access log', labelUk: 'Слідкувати за логом' },
            { command: 'tail -f /var/log/nginx/access.log | grep " 5[0-9][0-9] "', label: '5xx errors only', labelUk: 'Тільки 5xx помилки' },
            { command: 'awk \'{ print $9 }\' /var/log/nginx/access.log | sort | uniq -c | sort -rn | head', label: 'Top status codes', labelUk: 'Топ кодів статусу' },
          ],
        },
        { id: 'nginx-error-log', title: 'Error log (tail)', titleUk: 'Лог помилок', command: 'tail -f /var/log/nginx/error.log', description: 'Follow nginx error log in real-time' },
        { id: 'nginx-sites', title: 'List enabled sites', titleUk: 'Увімкнені сайти', command: 'ls -la /etc/nginx/sites-enabled/', description: 'Show all enabled nginx virtual hosts' },
      ],
    },
    {
      id: 'git',
      name: 'Git',
      nameUk: 'Git',
      icon: '🔀',
      items: [
        {
          id: 'git-status', title: 'Status', titleUk: 'Статус',
          command: 'git status',
          description: 'Show working tree status',
          descriptionUk: 'Показує стан робочого дерева: змінені, нові та проіндексовані файли.',
          syntax: 'git status [OPTIONS] [PATH...]',
          options: [
            { flag: '-s, --short', desc: 'Short format output', descUk: 'Скорочений формат виводу' },
            { flag: '-b, --branch', desc: 'Show branch info', descUk: 'Показати інформацію про гілку' },
            { flag: '--porcelain', desc: 'Machine-readable output', descUk: 'Машиночитаний вивід' },
            { flag: '-u', desc: 'Show untracked files', descUk: 'Показати невідстежувані файли' },
          ],
          examples: [
            { command: 'git status', label: 'Full status', labelUk: 'Повний статус' },
            { command: 'git status -s', label: 'Short format', labelUk: 'Скорочений формат' },
            { command: 'git status --porcelain', label: 'Scripting format', labelUk: 'Для скриптів' },
          ],
        },
        { id: 'git-log', title: 'Log (oneline)', titleUk: 'Лог (стиснений)', command: 'git log --oneline -20', description: 'Show last 20 commits in compact one-line format' },
        { id: 'git-pull', title: 'Pull', titleUk: 'Pull', command: 'git pull', description: 'Fetch and merge changes from remote' },
        { id: 'git-fetch', title: 'Fetch all', titleUk: 'Fetch all', command: 'git fetch --all', description: 'Fetch all remotes without merging' },
        { id: 'git-stash', title: 'Stash', titleUk: 'Сташ', command: 'git stash', description: 'Save current changes to stash' },
        { id: 'git-stash-pop', title: 'Stash pop', titleUk: 'Сташ відновити', command: 'git stash pop', description: 'Apply the latest stash and remove it' },
        { id: 'git-reset', title: 'Reset hard to origin', titleUk: 'Reset до origin', command: 'git reset --hard origin/$(git branch --show-current)', description: 'Discard all local changes and sync with remote branch' },
        { id: 'git-branches', title: 'Branches', titleUk: 'Гілки', command: 'git branch -a', description: 'List all local and remote branches' },
        { id: 'git-diff', title: 'Diff staged', titleUk: 'Diff staged', command: 'git diff --cached', description: 'Show changes staged for the next commit' },
      ],
    },
    {
      id: 'mysql',
      name: 'MySQL',
      nameUk: 'MySQL',
      icon: '🗄',
      items: [
        { id: 'mysql-connect', title: 'Connect root', titleUk: 'Підключитися root', command: 'mysql -u root -p', description: 'Connect to MySQL server as root' },
        { id: 'mysql-list-db', title: 'List databases', titleUk: 'Список БД', command: 'mysql -u root -p -e "SHOW DATABASES;"', description: 'List all databases' },
        { id: 'mysql-dump', title: 'Dump database', titleUk: 'Дамп бази', command: 'mysqldump -u root -p <dbname> > dump.sql', description: 'Export a database to a SQL dump file' },
        { id: 'mysql-import', title: 'Import dump', titleUk: 'Імпорт дампу', command: 'mysql -u root -p <dbname> < dump.sql', description: 'Import a SQL dump file into a database' },
        { id: 'mysql-processlist', title: 'Show processlist', titleUk: 'Процеси MySQL', command: 'mysql -u root -p -e "SHOW PROCESSLIST;"', description: 'Show running MySQL queries/connections' },
        { id: 'mysql-tablesize', title: 'Tables size', titleUk: 'Розмір таблиць', command: "mysql -u root -p -e \"SELECT table_schema, ROUND(SUM(data_length+index_length)/1024/1024,2) AS 'MB' FROM information_schema.tables GROUP BY table_schema;\"", description: 'Show size of each database in MB' },
      ],
    },
    {
      id: 'firewall',
      name: 'Firewall',
      nameUk: 'Файрвол',
      icon: '🛡',
      items: [
        {
          id: 'ufw-status', title: 'UFW status', titleUk: 'Статус UFW',
          command: 'ufw status verbose',
          description: 'Show UFW firewall status and all rules',
          descriptionUk: 'Показує статус UFW файрволу та всі правила.',
          syntax: 'ufw [OPTIONS] COMMAND',
          options: [
            { flag: 'status', desc: 'Show firewall status', descUk: 'Показати статус файрволу' },
            { flag: 'status verbose', desc: 'Detailed status with rules', descUk: 'Детальний статус з правилами' },
            { flag: 'allow PORT', desc: 'Allow traffic on port', descUk: 'Дозволити трафік на порту' },
            { flag: 'deny PORT', desc: 'Deny traffic on port', descUk: 'Заблокувати трафік на порту' },
            { flag: 'delete N', desc: 'Delete rule number N', descUk: 'Видалити правило N' },
          ],
          examples: [
            { command: 'ufw status verbose', label: 'Full status', labelUk: 'Повний статус' },
            { command: 'ufw allow 22/tcp', label: 'Allow SSH', labelUk: 'Дозволити SSH' },
            { command: 'ufw deny 23', label: 'Block Telnet', labelUk: 'Заблокувати Telnet' },
            { command: 'ufw delete 3', label: 'Delete rule #3', labelUk: 'Видалити правило #3' },
          ],
        },
        { id: 'ufw-allow-80', title: 'Allow port 80', titleUk: 'Дозволити порт 80', command: 'ufw allow 80/tcp' },
        { id: 'ufw-allow-443', title: 'Allow port 443', titleUk: 'Дозволити порт 443', command: 'ufw allow 443/tcp' },
        { id: 'iptables-list', title: 'iptables rules', titleUk: 'Правила iptables', command: 'iptables -L -n -v', description: 'List all iptables rules with packet counts' },
      ],
    },
    {
      id: 'osc',
      name: 'Terminal (OSC)',
      nameUk: 'Термінал (OSC)',
      icon: '⎋',
      items: [
        {
          id: 'osc52-copy',
          title: 'Copy to local clipboard (OSC 52)',
          titleUk: 'Скопіювати у локальний буфер (OSC 52)',
          command: `printf '\\033]52;c;%s\\a' "$(printf '%s' 'hello from remote' | base64 | tr -d '\\n')"`,
          description: 'Send text from the remote host straight into the local clipboard via OSC 52. Useful inside tmux/vim over SSH — no need to select with the mouse.',
          descriptionUk: 'Надсилає текст з віддаленого хоста напряму в локальний буфер обміну через OSC 52. Корисно всередині tmux/vim по SSH — не треба нічого виділяти мишкою. SENU підтримує цю послідовність.',
          syntax: `printf '\\033]52;c;<base64>\\a'`,
          options: [
            { flag: 'c', desc: 'Clipboard selection (c=clipboard, p=primary, s=select, q=cut-buffers)', descUk: 'Селекція (c=clipboard, p=primary, s=select, q=cut-buffers)' },
            { flag: '<base64>', desc: 'Payload must be base64-encoded UTF-8; use `?` to query (SENU ignores reads for security)', descUk: 'Вміст має бути base64-UTF-8; `?` означає запит (SENU ігнорує читання з міркувань безпеки)' },
          ],
          examples: [
            { command: `echo -n "file://$PWD/$(ls | fzf)" | base64 | xargs -I{} printf '\\033]52;c;%s\\a' '{}'`, label: 'Copy picked file path', labelUk: 'Копіювати шлях обраного файлу' },
            { command: `pbcopy() { printf '\\033]52;c;%s\\a' "$(base64 | tr -d '\\n')"; }; echo hi | pbcopy`, label: 'Define pbcopy() alias for a session', labelUk: 'Оголосити pbcopy() на час сесії' },
            { command: `cat ~/.ssh/id_ed25519.pub | base64 | tr -d '\\n' | xargs -I{} printf '\\033]52;c;%s\\a' '{}'`, label: 'Copy public key to local clipboard', labelUk: 'Копіювати публічний ключ' },
          ],
          tags: ['osc', 'clipboard', 'supported'],
        },
        {
          id: 'osc-title',
          title: 'Set window title (OSC 0/2)',
          titleUk: 'Змінити заголовок вікна (OSC 0/2)',
          command: `printf '\\033]0;%s\\a' "$(whoami)@$(hostname) — $(pwd)"`,
          description: 'Set the terminal window title via OSC 0 (icon+title) or OSC 2 (title only). Common inside PROMPT_COMMAND / PS1.',
          descriptionUk: 'Задає заголовок вікна терміналу через OSC 0 (іконка+заголовок) або OSC 2 (лише заголовок). Часто вставляють у PROMPT_COMMAND / PS1. NB: SENU поки не читає ці послідовності — він показує назву з tab.label.',
          syntax: `printf '\\033]0;<text>\\a'`,
          options: [
            { flag: '0', desc: 'Set both icon name and window title', descUk: 'Встановити іконку і заголовок' },
            { flag: '1', desc: 'Set icon name only', descUk: 'Лише іконку' },
            { flag: '2', desc: 'Set window title only', descUk: 'Лише заголовок' },
          ],
          examples: [
            { command: `export PROMPT_COMMAND='printf "\\033]0;%s@%s:%s\\a" "$USER" "$HOSTNAME" "$PWD"'`, label: 'Live-update title from prompt', labelUk: 'Оновлювати заголовок з промпту' },
            { command: `PS1='\\[\\033]0;\\u@\\h: \\w\\a\\]'"$PS1"`, label: 'Embed into PS1', labelUk: 'Вбудувати у PS1' },
          ],
          tags: ['osc', 'title'],
        },
        {
          id: 'osc8-hyperlink',
          title: 'Clickable hyperlink (OSC 8)',
          titleUk: 'Клікабельне посилання (OSC 8)',
          command: `printf '\\033]8;;https://example.com\\033\\\\Click me\\033]8;;\\033\\\\\\n'`,
          description: 'Emit a clickable hyperlink in the terminal output. Terminal needs OSC 8 support — SENU does not render these yet (tracked for future).',
          descriptionUk: 'Виводить клікабельне посилання. Потрібна підтримка OSC 8 у терміналі — SENU поки не рендерить (у планах).',
          syntax: `\\033]8;<params>;<uri>\\033\\\\<text>\\033]8;;\\033\\\\`,
          options: [
            { flag: '<params>', desc: 'Optional `id=<key>` to group fragments; usually empty', descUk: 'Опц. `id=<key>` для групування фрагментів' },
            { flag: '<uri>', desc: 'URL (http/https/file/mailto)', descUk: 'URL (http/https/file/mailto)' },
          ],
          examples: [
            { command: `printf '\\033]8;;file://%s\\033\\\\%s\\033]8;;\\033\\\\\\n' "$PWD/error.log" "error.log"`, label: 'Link to local file in output', labelUk: 'Посилання на локальний файл' },
            { command: `git log --format='%h %s %H' | awk '{printf "\\033]8;;https://github.com/owner/repo/commit/%s\\033\\\\%s\\033]8;;\\033\\\\ %s\\n",$3,$1,$2}'`, label: 'Linkify git log to GitHub', labelUk: 'Перетворити git log на посилання GitHub' },
          ],
          tags: ['osc', 'hyperlink', 'todo'],
        },
        {
          id: 'osc7-cwd',
          title: 'Report CWD (OSC 7)',
          titleUk: 'Повідомити CWD (OSC 7)',
          command: `printf '\\033]7;file://%s%s\\a' "$HOSTNAME" "$PWD"`,
          description: 'Tell the terminal emulator the current working directory. Modern terminals use this to open new tabs in the same folder. SENU does not act on OSC 7 yet.',
          descriptionUk: 'Повідомляє емулятор про поточну директорію. Сучасні термінали використовують це щоб нова вкладка відкривалась у тому ж каталозі. SENU поки не обробляє OSC 7.',
          syntax: `printf '\\033]7;file://<host><path>\\a'`,
          examples: [
            { command: `PROMPT_COMMAND='printf "\\033]7;file://%s%s\\a" "$HOSTNAME" "$PWD"'"$PROMPT_COMMAND"`, label: 'Auto-emit on every prompt', labelUk: 'Надсилати при кожному промпті' },
          ],
          tags: ['osc', 'cwd', 'todo'],
        },
        {
          id: 'osc133-prompt',
          title: 'Shell integration markers (OSC 133)',
          titleUk: 'Маркери prompt-інтеграції (OSC 133)',
          command: `PS1='\\[\\033]133;A\\a\\]'"$PS1"'\\[\\033]133;B\\a\\]'`,
          description: 'iTerm2/WezTerm/Ghostty-style prompt markers (A=prompt start, B=prompt end, C=output start, D=command end). Enables "jump between prompts" navigation. SENU could implement this later for Ctrl+↑/↓ navigation — tracked as future work.',
          descriptionUk: 'Маркери prompt-інтеграції у стилі iTerm2/WezTerm/Ghostty (A=початок промпту, B=кінець, C=початок виводу, D=кінець команди). Дозволяють навігацію між промптами. SENU може реалізувати це пізніше для Ctrl+↑/↓ між командами — у планах.',
          syntax: `\\033]133;<A|B|C|D>[;exit=<code>]\\a`,
          options: [
            { flag: 'A', desc: 'Prompt start', descUk: 'Початок промпту' },
            { flag: 'B', desc: 'Prompt end / command input start', descUk: 'Кінець промпту / початок вводу' },
            { flag: 'C', desc: 'Command output start', descUk: 'Початок виводу команди' },
            { flag: 'D;exit=N', desc: 'Command finished with exit code N', descUk: 'Команда завершилась з exit code N' },
          ],
          tags: ['osc', 'shell-integration', 'todo'],
        },
        {
          id: 'osc-reset',
          title: 'Reset terminal colors (OSC 104/110/111/112)',
          titleUk: 'Скинути кольори терміналу (OSC 104/110/111/112)',
          command: `printf '\\033]104\\a\\033]110\\a\\033]111\\a\\033]112\\a'`,
          description: 'Reset the ANSI palette, default foreground, default background, and cursor color to terminal defaults. Useful after a misbehaving TUI leaks custom colors.',
          descriptionUk: 'Скидає ANSI палітру, колір тексту, фону та курсору до дефолтних. Корисно після TUI-програми, яка залишила свої кольори.',
          syntax: `\\033]<104|110|111|112>\\a`,
          tags: ['osc', 'reset'],
        },
      ],
    },
    {
      id: 'php',
      name: 'PHP / Laravel',
      nameUk: 'PHP / Laravel',
      icon: '🐘',
      items: [
        { id: 'php-v', title: 'PHP version', titleUk: 'Версія PHP', command: 'php -v', description: 'Display PHP version and build information' },
        { id: 'artisan-about', title: 'Artisan status', titleUk: 'Artisan статус', command: 'php artisan about', description: 'Display application environment information' },
        { id: 'artisan-clear', title: 'Clear all caches', titleUk: 'Очистити кеш', command: 'php artisan optimize:clear', description: 'Clear config, route, view, and application caches' },
        { id: 'artisan-migrate', title: 'Run migrations', titleUk: 'Запустити міграції', command: 'php artisan migrate --force', description: 'Run database migrations in production mode' },
        { id: 'artisan-queue', title: 'Queue restart', titleUk: 'Перезапустити черги', command: 'php artisan queue:restart', description: 'Gracefully restart queue workers after next job' },
        { id: 'artisan-storage', title: 'Storage link', titleUk: 'Посилання storage', command: 'php artisan storage:link', description: 'Create symbolic link from public/storage to storage/app/public' },
        { id: 'composer-install', title: 'Composer install', titleUk: 'Composer install', command: 'composer install --no-dev --optimize-autoloader', description: 'Install production dependencies with optimized autoloader' },
      ],
    },
  ],
}
